// ACTION FOR REDUX
export const ADD_TODOS = "ADD_TODOS"
export const DELETE_TODOS = "DELETE_TODOS"
export const UPDATE_TODOS = "UPDATE_TODOS"

// ACTION FOR REDUX-SAGA
export const ADD_TODOS_SAGA = "ADD_TODOS_SAGA"
export const UPDATE_TODOS_SAGA = "UPDATE_TODOS_SAGA"
export const DELETE_TODOS_SAGA = "DELETE_TODOS_SAGA"
